In [57]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [22]:
X,y = load_breast_cancer(return_X_y=True)


In [24]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state=3)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [26]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [27]:
clf1.fit(X_train , y_train)
clf2.fit(X_train , y_train)

C:\Users\arups\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [28]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [33]:
print("Accuracy of Logistic Regression", accuracy_score(y_pred1 , y_test))
print("Accuracy of Decision Trees",accuracy_score(y_pred2 , y_test))

Accuracy of Logistic Regression 0.9035087719298246
Accuracy of Decision Trees 0.8947368421052632


In [36]:
confusion_matrix(y_test,y_pred1)

array([[33,  7],
       [ 4, 70]], dtype=int64)

In [39]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  33   7
1   4  70

In [40]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test , y_pred1) , columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  33   7
1   4  70

In [41]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Regression Prediction'] = y_pred2

In [42]:
result.sample(20)

Actual Label  Logistic Regression Prediction  \
85              0                               1   
73              0                               0   
68              0                               0   
7               1                               1   
112             1                               1   
79              0                               0   
26              1                               1   
39              0                               0   
90              0                               0   
36              1                               1   
106             0                               0   
75              0                               0   
77              0                               0   
21              1                               1   
110             1                               1   
91              0                               0   
18              0                               0   
97              0                               0   
103             1                               1   
57              1                               0   

     Decision Regression Prediction  
85                                0  
73                                0  
68                                0  
7                                 1  
112                               1  
79                                0  
26                                1  
39                                0  
90                                0  
36                                1  
106                               0  
75                                0  
77                                0  
21                                1  
110                               1  
91                                0  
18                                0  
97                                0  
103                               1  
57                                0

In [43]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [44]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  33   7
1   4  70
--------------------------------------------------
Precision -  0.9090909090909091
Recall -  0.9459459459459459
F1 score -  0.9271523178807948


In [45]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  36   4
1   8  66
--------------------------------------------------
Precision -  0.9428571428571428
Recall -  0.8918918918918919
F1 score -  0.9166666666666667


In [46]:
precision_score(y_test , y_pred1 , average=None)
# Here for both  0 and 1 precision_score is calculated but in Binary Classification we take only 0 th value
# average=None means har class ka precision alag se dikhai dega

array([0.89189189, 0.90909091])

In [47]:
precision_score(y_test , y_pred2 , average=None)

array([0.81818182, 0.94285714])

In [49]:
recall_score(y_test , y_pred1 , average=None)

array([0.825     , 0.94594595])

In [50]:
recall_score(y_test , y_pred2 , average=None)

array([0.9       , 0.89189189])

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.89      0.82      0.86        40
           1       0.91      0.95      0.93        74

    accuracy                           0.90       114
   macro avg       0.90      0.89      0.89       114
weighted avg       0.90      0.90      0.90       114



In [ ]:
# f1_score(y_test,y_pred1,average='weighted')
# f1_score(y_test,y_pred1,average=None)