In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn import datasets
from sklearn.linear_model import LinearRegression

In [2]:
data = load_iris()

X = data['data']
y = data['target']

In [3]:
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state = 2 , test_size = 4)

In [4]:
X_train # changing random_state X_train also changed 

array([[4.8, 3.4, 1.9, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5. , 3. , 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6. , 3.4, 4.5, 1.6],
       [6.5, 2.8, 4.6, 1.5],
       [4.5, 2.3, 1.3, 0.3],
       [5.7, 2.9, 4.2, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [5.5, 2.5, 4. , 1.3],
       [6.7, 3. , 5. , 1.7],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [5.6, 2.7, 4.2, 1.3],
       [6.3, 2.3, 4.4, 1.3],
       [4.7, 3.2, 1.6, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.8, 1.9, 0.4],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.9, 3.6, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.4, 3. , 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2

In [5]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train , y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test , y_pred)

1.0

In [6]:
X = np.random.random((25,5))
y = np.random.randint(low=0 , high=2 , size = (25))

In [7]:
kf = KFold(n_splits=6)
for train_index , test_index in kf.split(X):
    print(train_index , test_index)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [0 1 2 3 4]
[ 0  1  2  3  4  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 13 14 15 16 17 18 19 20 21 22 23 24] [ 9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 17 18 19 20 21 22 23 24] [13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 21 22 23 24] [17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [21 22 23 24]


# cross_val_score (classification)

In [8]:
data = load_iris()

X = data['data']
y = data['target']

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X , y)
scores = cross_val_score(knn , X , y , scoring='accuracy' , cv=10 )
scores

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [10]:
scores.mean()

0.9666666666666668

In [11]:
for i in range(1,21):
    knn = KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(knn , X , y , scoring='accuracy' , cv=10 )
    print(i , scores.mean())

1 0.96
2 0.9533333333333334
3 0.9666666666666666
4 0.9666666666666666
5 0.9666666666666668
6 0.9666666666666668
7 0.9666666666666668
8 0.9666666666666668
9 0.9733333333333334
10 0.9666666666666668
11 0.9666666666666668
12 0.9733333333333334
13 0.9800000000000001
14 0.9733333333333334
15 0.9733333333333334
16 0.9733333333333334
17 0.9733333333333334
18 0.9800000000000001
19 0.9733333333333334
20 0.9800000000000001


In [12]:
data = datasets.load_diabetes()

X = data['data']
y = data['target']

In [13]:
reg = LinearRegression()
scores = np.mean(cross_val_score(reg , X , y , cv=10 , scoring='r2'))
print(scores)

0.4619602420450601
