In [2]:
import numpy as np
import random

In [5]:
type(np.random.random(1))
print(np.random.random(1)) # This will give value between 0-1 

[0.91820664]


In [4]:
# DIFFERENCE BETWEEN rand() and random()

np.random.random((3 , 2))
np.random.rand(3 , 2)

array([[0.01988692, 0.46542759],
       [0.32506542, 0.87204662],
       [0.55993049, 0.59060959]])

In [8]:
np.round(np.random.random((3 , 3)) , 1)

array([[0.6, 0.5, 0.7],
       [0.8, 0.2, 0.1],
       [1. , 0.3, 0.8]])

In [12]:
np.random.randint(1 , 4 , (2 , 4 , 4))
# Here (2,4,4) means matrix contain 2 value , each value contain 4 value and among these 4 value's each part contain 4 values


array([[[3, 1, 2, 1],
        [3, 2, 1, 2],
        [3, 3, 3, 2],
        [2, 1, 2, 2]],

       [[2, 3, 1, 2],
        [3, 2, 2, 1],
        [3, 3, 3, 2],
        [3, 2, 3, 3]]])

In [14]:
np.random.randint(1 , 4)

1

In [15]:
np.random.seed(10)
np.random.randint(1 , 5 , (1 , 6))

array([[2, 2, 1, 4, 1, 2]])

In [17]:
np.random.seed(10) # .seed(value) it's a type of Locking function.
# Here i specified value 10. the array we got using of np.random.randint(1 , 5 , (1 , 6)) function,
# the same array we can get if we specified the value = 10
np.random.randint(1 , 5 , (1 , 6))

array([[2, 2, 1, 4, 1, 2]])

In [22]:
np.random.randint(0, 10, size=(3,), dtype=int)


array([4, 6, 8])

In [24]:
np.random.rand(3)
np.random.rand(3  , 3)

array([[0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399],
       [0.61776698, 0.51313824, 0.65039718]])

In [25]:
np.random.randn(3 , 3)

array([[ 1.2616859 ,  0.41765968,  0.89395769],
       [ 0.04735517, -0.60842552, -0.26854813],
       [-0.66630197, -0.34401183,  0.80705192]])

In [26]:
x = [2 , 7 , 44 , 66 , 45]

for i in range(10):
    print(np.random.choice(x))

44
2
2
45
45
2
2
44
45
44


In [28]:
np.random.permutation(x) # It's use for array Shuffling

array([ 7, 66,  2, 45, 44])

In [1]:
import numpy as np

# Set the seed value
np.random.seed(10)

# Print the array
print(np.random.randint(1, 5, (1, 6)))

# Reset the seed value
np.random.seed(None)

# Print the array
print(np.random.randint(1, 5, (1, 6)))

[[2 2 1 4 1 2]]
[[2 3 2 3 4 1]]


In [2]:
x = np.array([5 , 4 , 3 , 5])
np.random.choice(x)

5

In [3]:
np.random.choice(6, 3) # random value btw 0-6 and total 3 value

array([4, 4, 5])

In [10]:
np.random.choice((0,5), 3) # random shuffling 0 and 5 and total 3 value

array([0, 5, 0])

In [11]:
np.random.permutation(np.arange(5))[:3]

array([4, 0, 2])

In [12]:
np.random.choice(6, 3 , replace = True)

array([2, 1, 3])