In [2]:
import numpy as np

In [4]:
arr_1d = np.arange(1 , 13 , 2)
print(arr_1d)

[ 1  3  5  7  9 11]


In [40]:
np.linspace(1 , 5 , 4 , dtype = int) # Here I want values between 1-5 and i want 4 values

# np.linespace(1 , 5 , 4 , dtype = int) OUT-PUT is array([ True,  True,  True,  True])

array([1, 2, 3, 5])

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with shape (2, 3)
reshaped_arr = np.reshape(arr, (2, 3), order='F')
# order = 'C' represent row-major order
# order = 'F' represent column-major order
print("Original array:")
print(arr)
print("Reshaped array:")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 3 5]
 [2 4 6]]


In [6]:
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
arr.reshape(2 , 3 )

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr = np.arange(1 , 13).reshape(2 , 3 , 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
print(arr.ravel())
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
print(arr.transpose())

[[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]


In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along axis 0 (column)
sum_axis_0 = np.sum(arr, axis=0)
print(sum_axis_0)
# Output: [5 7 9]

# Sum along axis 1 (row)
sum_axis_1 = np.sum(arr, axis=1)
print(sum_axis_1)
# Output: [ 6 15]


[5 7 9]
[ 6 15]


In [19]:
arr = np.arange(1 , 13).reshape(2 , 3 , 2)
print(arr)
print(arr.max(axis = 1)) # In pandas axis=1 means columns but In Numpy axis = 1 means row

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 5  6]
 [11 12]]


In [22]:
arr.argmax()

11

In [27]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

result = np.column_stack((a, b))
column_sum = np.sum(result, axis=0)

print(column_sum)
print(result)


[15 40]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [28]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.row_stack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]


In [32]:
arr = np.arange(1 , 7).reshape(2 , 3)
print(np.mean(arr))
print(np.sqrt(arr))
print(np.std(arr))

3.5
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [33]:
print(np.exp(arr))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [37]:
print(np.log(arr)) # EACH ELEMENT log VALUE WE GOT

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [38]:
print(np.log2(arr)) # # EACH ELEMENT log VALUE WE GOT WHICH BASE IS 2

[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]
