In [2]:
import numpy as np

In [4]:
arr_1d = np.array([1 , 2 , 3 , 4 , 5])
print(arr_1d)

[1 2 3 4 5]


In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
arr_2d = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
print(f'size of array is {arr_2d.size} and dimention of the array is {arr_2d.ndim}')

size of array is 6 and dimention of the array is 2


In [12]:
row , col = arr_2d.shape
print(row)
print(arr_2d.dtype)

2
int32
