In [1]:
import numpy as np

In [5]:
arr = np.array([[[1 , 2 , 3] , [4 , 5 , 6]] ,
                [[1 , 2 , 3] , [4 , 5 , 6]]])
print(arr.shape)

# Here (2, 2, 3) means 2 row , each row has 2 element , per element contain 3 values

(2, 2, 3)


In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
arr_2d = np.ones((2 , 3))
print(arr_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
mx_1s = np.ones((3 , 4) , dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
mx_0r = np.zeros((4 , 6) , dtype = bool)
print(mx_0r)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [11]:
mx_0r = np.zeros((4 , 6) , dtype = str)
print(mx_0r)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [12]:
string = ''

print(bool(string))

False


In [13]:
mx_empty = np.empty((3 , 3))
print(mx_empty)

[[4.67296746e-307 1.69121096e-306 1.86921686e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 1.14739303e-227]]
