In [17]:
import numpy as np

In [25]:
# HOW TO KNOW AN ARRAY IS RESHAPABLE OR NOT ?
# Ans. Array's shape's product == User shape's product.

import numpy as np

def is_reshapable(arr , shape):
    return np.prod(arr.shape) == np.prod(shape)
        
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
shape = (3 , 1)
print(is_reshapable(arr , shape))
    

False


In [3]:
arr1 = np.arange(1 , 10).reshape(3 , 3)
arr2 = np.arange(10 , 19).reshape(3 , 3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [8]:
np.add(arr1 , arr2)
np.subtract(arr1 , arr2)
np.round(np.divide(arr1 , arr2) , 1)
np.multiply(arr1 , arr2) # THIS IS NOT ACTUAL MATRIX MULTIPLICATION PRODUCT

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [10]:
print(arr1.dot(arr2))

#     --OR--

print(arr1 @ arr2)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [16]:
print(f"THE MAXIMUM VALUE OF arr1 MATRIX IS {arr1.max()}\nTHE INDEX POSITION OF MAXIMUM VALUE OF arr1 MATRIX IS {arr1.argmax()}")

THE MAXIMUM VALUE OF arr1 MATRIX IS 9
THE INDEX POSITION OF MAXIMUM VALUE OF arr1 MATRIX IS 8
