In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1 , 17).reshape(4 , 4)
arr2 = np.arange(17 , 33).reshape(4 , 4)
print(arr1 , '\n')
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [15]:
arr3 = np.concatenate((arr1 , arr2) , axis = 1) 
print(arr3)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [4]:
np.vstack((arr1 , arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [5]:
np.hstack((arr1 , arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [6]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
array1 , array2 = np.split(arr1 , 2) # Here We have to set the value in such way that 
                                     # it can divide the row in equal part
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np

# Create an example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into unequal divisions
indices = [3, 6]  # Indices at which to split the array
result = np.split(arr, indices)

print(result)
# Print the resulting sub-arrays
for sub_array in result:
    print(sub_array)
    
# we specify 3 and 6, which means the array will be split into three parts:
# the elements before index 3, the elements between indices 3 and 6, and the elements after index 6.

arr2 = np.arange(17 , 33)
for i in np.split(arr2 , [5,12]):
    print(i)

[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10])]
[1 2 3]
[4 5 6]
[ 7  8  9 10]


In [11]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr1 = np.arange(1 , 17).reshape(4 , 4)
np.split(arr1, 2 , axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
[ 1,  2,  3,  4],
[ 5,  6,  7,  8],

In [ ]:
[ 9, 10, 11, 12],
[13, 14, 15, 16],